@startuml ユースケース図
' left to right direction
skinparam actorStyle Hollow
actor 社畜 #pink;line:red;line.bold;text:blue;line:green;line.bold;
package 販売管理システム {
usecase 出荷状況を登録する as T
usecase 出荷状況を確認する as K
}
社畜 --> T
社畜 --> K

@enduml